# Julia100 Exercise
[これ](https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.ipynb)をJuliaでやってく.  
もう１つのJulia100exerciseも途中まで(48個くらい？)だけどあるっぽい[こちら](https://github.com/chezou/julia-100-exercises/blob/master/README.md)  

Julia version: 1.2.0

**目指すは世界初()のJulia100 Exercise作成**

全てに所感と考察を絶対述べる縛りで行きます.

## 1. 行列ライブラリを読み込む（難易度１）

**これはimportの必要なしJuliaに関しては行列計算できる**  
ドキュメントは[こちら](https://docs.julialang.org/en/v1/index.html)

## 2. Juliaのバージョンを確認する（難易度１）

In [1]:
VERSION

v"1.2.0"

In [18]:
?VERSION　# ?でドキュメントは変わらないっぽい

search: VERSION VersionNumber versioninfo reverseind



```
VERSION
```

A `VersionNumber` object describing which version of Julia is in use. For details see [Version Number Literals](@ref man-version-number-literals).


#### 所感・考察・調査
演算子の数とかドキュメントの充実さスゴない？(以下参照)

In [21]:
?

search: ⊻ ⊋ ⊊ ⊉ ⊈ ⊇ ⊆ ≥ ≤ ≢ ≡ ≠ ≉ ≈ ∪ ∩ ∛ √ ∘ ∌ ∋ ∉ ∈ ℯ π ÷ ~ | ^ \ > < : / - +



**Welcome to Julia 1.2.0.** The full manual is available at

```
https://docs.julialang.org/
```

as well as many great tutorials and learning resources:

```
https://julialang.org/learning/
```

For help on a specific function or macro, type `?` followed by its name, e.g. `?cos`, or `?@time`, and press enter. Type `;` to enter shell mode, `]` to enter package mode.


In [27]:
?cos

search: cos cosh cosd cosc cospi acos acosh acosd sincos const close isconst



```
cos(x)
```

Compute cosine of `x`, where `x` is in radians.

---

```
cos(A::AbstractMatrix)
```

Compute the matrix cosine of a square matrix `A`.

If `A` is symmetric or Hermitian, its eigendecomposition ([`eigen`](@ref)) is used to compute the cosine. Otherwise, the cosine is determined by calling [`exp`](@ref).

# Examples

```jldoctest
julia> cos(fill(1.0, (2,2)))
2×2 Array{Float64,2}:
  0.291927  -0.708073
 -0.708073   0.291927
```


## 3. サイズ10の零ベクトルを作成する（難易度１）

In [6]:
a = zeros(Float64,10,1)

10×1 Array{Float64,2}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [42]:
zeros(10,1) # 型は指定しないとFloat64

10×1 Array{Float64,2}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [8]:
zeros(10) # 配列になってるっぽい？

10-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [5]:
A = zeros(Int64,2,2) 

2×2 Array{Int64,2}:
 0  0
 0  0

#### 所感・考察・調査
あくまでも行列演算ライブラリではないと言うのが`zeros(10)`の結果から読み取れる

## 4. 行列のメモリサイズを確認するには？（難易度１）

In [36]:
sizeof(a)　

80

In [43]:
sizeof(A) #行列じゃなくてももちろん使える

32

In [41]:
# ?size #?のサーチで見つけた。。。

In [40]:
?sizeof

search: sizeof



```
sizeof(T::DataType)
sizeof(obj)
```

Size, in bytes, of the canonical binary representation of the given `DataType` `T`, if any. Size, in bytes, of object `obj` if it is not `DataType`.

# Examples

```jldoctest
julia> sizeof(Float32)
4

julia> sizeof(ComplexF64)
16

julia> sizeof(1.0)
8

julia> sizeof([1.0:10.0;])
80
```

If `DataType` `T` does not have a specific size, an error is thrown.

```jldoctest
julia> sizeof(AbstractArray)
ERROR: Abstract type AbstractArray does not have a definite size.
Stacktrace:
[...]
```

---

```
sizeof(str::AbstractString)
```

Size, in bytes, of the string `str`. Equal to the number of code units in `str` multiplied by the size, in bytes, of one code unit in `str`.

# Examples

```jldoctest
julia> sizeof("")
0

julia> sizeof("∀")
3
```


#### 所感・考察・調査
元のnumpy100見たく`size`とか`itemsize`でやるのかなーと思ってたけど`sizeof()`一発で行けるっぽい

## 5. 任意のfunction等のドキュメントを得るには？（難易度１）

In [44]:
?sin

search: sin sinh sind sinc sinpi sincos asin using isinf asinh asind isinteger



```
sin(x)
```

Compute sine of `x`, where `x` is in radians.

---

```
sin(A::AbstractMatrix)
```

Compute the matrix sine of a square matrix `A`.

If `A` is symmetric or Hermitian, its eigendecomposition ([`eigen`](@ref)) is used to compute the sine. Otherwise, the sine is determined by calling [`exp`](@ref).

# Examples

```jldoctest
julia> sin(fill(1.0, (2,2)))
2×2 Array{Float64,2}:
 0.454649  0.454649
 0.454649  0.454649
```


In [45]:
?fill

search: fill fill! finally findall filter filter! filesize filemode isfile



```
fill(x, dims)
```

Create an array filled with the value `x`. For example, `fill(1.0, (5,5))` returns a 5×5 array of floats, with each element initialized to `1.0`.

# Examples

```jldoctest
julia> fill(1.0, (5,5))
5×5 Array{Float64,2}:
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
```

If `x` is an object reference, all elements will refer to the same object. `fill(Foo(), dims)` will return an array filled with the result of evaluating `Foo()` once.


#### 所感・考察・調査
`?`:ヘルプコマンドの便利さがスゴイ

## 06. 5番目の要素だけ1の大きさ10の零ベクトルを作る（難易度1）

In [5]:
a6 = zeros(10,1)
a6[5]=1

1

In [6]:
a6

10×1 Array{Float64,2}:
 0.0
 0.0
 0.0
 0.0
 1.0
 0.0
 0.0
 0.0
 0.0
 0.0

#### 所感・考察・調査
indexの始まりが0スタートでないことに注意

## 07. 10~49の範囲のベクトルを作成する（難易度1）

In [30]:
LinRange(10,49,49-9)

40-element LinRange{Float64}:
 10.0,11.0,12.0,13.0,14.0,15.0,16.0,17.0,…,43.0,44.0,45.0,46.0,47.0,48.0,49.0

In [61]:
print([ 10 + 1*x for x in 1:39, y in 1:1 ])

[11; 12; 13; 14; 15; 16; 17; 18; 19; 20; 21; 22; 23; 24; 25; 26; 27; 28; 29; 30; 31; 32; 33; 34; 35; 36; 37; 38; 39; 40; 41; 42; 43; 44; 45; 46; 47; 48; 49]

#### 所感・考察・調査
他に絶対いいやり方ありそう、要調査

#### 追記
調査結果

In [49]:
print([x for x = 10:49])

[10, 11, 12, 13, 14, 15, 16, 17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36, 37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49]

## 08. ベクトルを並びを反対にするには？(最初の要素を最後の要素に)（難易度1)

In [60]:
base_vec08=[ 10 + 1*x for x in 1:39, y in 1:1 ];

In [56]:
print(base_vec08[end:-1:1])

[49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11]

#### 所感・考察・調査
arrayのスライス?の使い方?  
`[始めるindex:step:終わりのindex]`,[参考](https://stackoverflow.com/questions/27411401/julia-reverse-n-dimensional-arrays)

In [59]:
print(base_vec08[end:-2:10])

[49, 47, 45, 43, 41, 39, 37, 35, 33, 31, 29, 27, 25, 23, 21]

## 09. 0~8の値をもつ3*3の行列を作成する

In [96]:
base09=[ x-1 for x in 1:9, y in 1:1 ];
ans09=reshape(base09,3,3)'

3×3 LinearAlgebra.Adjoint{Int64,Array{Int64,2}}:
 0  1  2
 3  4  5
 6  7  8

#### 所感・考察・調査
これはnumpyとほぼ同じ、転置するには`'`をつける。[参考](https://qiita.com/haru1843/items/3956dab2fd0d448cd02b)  
以下の書き方もある

In [7]:
reshape(0:8, 3, 3)'

3×3 LinearAlgebra.Adjoint{Int64,Base.ReshapedArray{Int64,2,UnitRange{Int64},Tuple{}}}:
 0  1  2
 3  4  5
 6  7  8

## 10. `[1,2,0,0,4,0]`から要素が0でないインデックスを見つける

In [2]:
base10=[1,2,0,0,4,0];

In [6]:
findall(x->x!=0,base10)

3-element Array{Int64,1}:
 1
 2
 5

#### 所感・考察・調査
他の条件での検索・行列への適用も可能.[参考](https://discourse.julialang.org/t/finding-position-of-element-in-an-array/12502)

## 11. 3*3の単位行列を作成する

In [2]:
using LinearAlgebra

In [4]:
Matrix{Float64}(I, 2, 2)

2×2 Array{Float64,2}:
 1.0  0.0
 0.0  1.0

#### 所感・考察・調査
線形代数系などを使う場合は`using`を用いる.[参考](https://www.reddit.com/r/Julia/comments/9cfosj/identity_matrix_in_julia_v10/)  
pkgでimportする必要もあるかも

## 12. 乱数で 3x3x3 配列を生成する

In [2]:
rand(3, 3, 3)

3×3×3 Array{Float64,3}:
[:, :, 1] =
 0.596368   0.0139274  0.870677
 0.547485   0.84639    0.730537
 0.0127367  0.71785    0.523963

[:, :, 2] =
 0.290247  0.401709  0.384823 
 0.29468   0.680223  0.0183093
 0.353845  0.105515  0.255638 

[:, :, 3] =
 0.531215  0.326404  0.0694056
 0.861704  0.668102  0.402493 
 0.165582  0.670954  0.66965  

#### 所感・考察・調査
`rand`を用いる.[参考](https://docs.julialang.org/en/v1/stdlib/Random/)  

## 13. 乱数で 10x10 配列を生成して、その最小値と最大値を見つける

In [7]:
ans13=rand(10, 10);

In [13]:
println(findmin(ans13))
println(findmax(ans13))

(0.005112553439780454, CartesianIndex(4, 3))
(0.9877986237343379, CartesianIndex(2, 1))


#### 所感・考察・調査
見つけた最小最大とindex(位置)が返される.
[参考](https://qiita.com/yshutaro/items/0e9a57d1977d4b65ccfc#findmin%E9%96%A2%E6%95%B0findmax%E9%96%A2%E6%95%B0)  
こちらも軸をdimで指定出来る.

In [23]:
println(findmin(ans13,dims=1))
println(findmin(ans13,dims=2))

([0.17669189181462874 0.1934329846430094 0.005112553439780454 0.06514074825436644 0.013729635176940036 0.01062104259287544 0.2264110966364623 0.020540626073598967 0.11947163941981254 0.11378571534468307], CartesianIndex{2}[CartesianIndex(10, 1) CartesianIndex(4, 2) CartesianIndex(4, 3) CartesianIndex(4, 4) CartesianIndex(8, 5) CartesianIndex(2, 6) CartesianIndex(9, 7) CartesianIndex(7, 8) CartesianIndex(4, 9) CartesianIndex(9, 10)])
([0.17699347206107663; 0.01062104259287544; 0.06547699196955681; 0.005112553439780454; 0.3145552489695298; 0.09183834781637068; 0.020540626073598967; 0.013729635176940036; 0.11378571534468307; 0.11513767577795564], CartesianIndex{2}[CartesianIndex(1, 9); CartesianIndex(2, 6); CartesianIndex(3, 3); CartesianIndex(4, 3); CartesianIndex(5, 3); CartesianIndex(6, 6); CartesianIndex(7, 8); CartesianIndex(8, 5); CartesianIndex(9, 10); CartesianIndex(10, 8)])


In [24]:
# ?findmin

## 14. 大きさ30の乱数のベクトルを生成して、その平均を求める

In [31]:
using Statistics

In [32]:
mean(rand(30))

0.5280760708329783

#### 所感・考察・調査
`Statistics`パッケージで各種統計量を使える.  [参考](https://docs.julialang.org/en/v1/stdlib/Statistics/)

## 15. 周囲が 1 で内部が 0 であるような2次元配列生成する

In [69]:
ans15=ones((10,10));
ans15[2:9,2:9].=0;
ans15

10×10 Array{Float64,2}:
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
 1.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0  1.0
 1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0  1.0

#### 所感・考察・調査
`ans15[2:-1,2:-1]`,こんな感じには指定できない?

## 16. 存在する行列の周りに0の境界線を引く

In [6]:
# import Pkg; Pkg.add("PaddedViews")

In [6]:
# import Pkg; Pkg.add("OffsetArrays")

In [7]:
using PaddedViews, OffsetArrays

In [34]:
A = OffsetArray(ones(4, 4), 3:6, 3:6)

4×4 OffsetArray(::Array{Float64,2}, 3:6, 3:6) with eltype Float64 with indices 3:6×3:6:
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0

In [36]:
PaddedView(0, A, (Base.OneTo(8), Base.OneTo(8)))

8×8 PaddedView{Float64,2,Tuple{Base.OneTo{Int64},Base.OneTo{Int64}},OffsetArray{Float64,2,Array{Float64,2}}}:
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0
 0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0
 0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0
 0.0  0.0  1.0  1.0  1.0  1.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0
 0.0  0.0  0.0  0.0  0.0  0.0  0.0  0.0

#### 所感・考察・調査
numpyよりも一手間かかるイメージ, [参考](https://github.com/JuliaArrays/PaddedViews.jl/issues/9)  
ここでは  

1. 1-2, 5-6のオフセットをもつ4*4の要素1.0の行列を作成(`OffsetArray`を使用)
2. PaddedViewにより1-2, 5-6のオフセットを0.0でパティングした8*8の行列を作成する 

と言う手順を取っている.

## 17. 以下の式の結果は?

In [38]:
0 * NaN

NaN

In [39]:
NaN == NaN

false

In [43]:
Inf>NaN

false

In [44]:
NaN-NaN

NaN

In [45]:
0.3 == 3 * 0.1

false

#### 所感・考察・調査
大体Pythonと同じ？

## 18. 対角成分の直下に 1,2,3,4 の成分を持つ 5x5 行列を生成する

#### 1. `diagind`を用いる
`diagind`:対象とした行列の対角要素のindexを返す. 第二引数で対象とする軸を選択す(今回は-1)

In [70]:
ans18_1=zeros(Int64,5,5);
ans18_1[diagind(base18, -1)] .= [x for x in 1:4];
ans18_1

5×5 Array{Int64,2}:
 0  0  0  0  0
 1  0  0  0  0
 0  2  0  0  0
 0  0  3  0  0
 0  0  0  4  0

#### 2. `Tridiagonal`を用いる

In [6]:
using LinearAlgebra

In [75]:
dl=[ x for x in 1:4 ];
d=zeros(Int64,5);
du=zeros(Int64,4);

In [95]:
ans18_2=Tridiagonal(dl,d,du)

5×5 Tridiagonal{Int64,Array{Int64,1}}:
 0  0  ⋅  ⋅  ⋅
 1  0  0  ⋅  ⋅
 ⋅  2  0  0  ⋅
 ⋅  ⋅  3  0  0
 ⋅  ⋅  ⋅  4  0

#### 追記:`diagm`を用いる
これが一番直感的かも, =>の前で軸?を指定

In [100]:
diagm(-1=>[ x for x in 1:4 ])

5×5 Array{Int64,2}:
 0  0  0  0  0
 1  0  0  0  0
 0  2  0  0  0
 0  0  3  0  0
 0  0  0  4  0

#### 所感・考察・調査
Tridiagonalは本来の使い方ではない気がするので前者の手法でやる方がいいかも  
diagindの使い方はほぼpythonの同じ使い方ができる.
[1の参考](https://stackoverflow.com/questions/49964360/in-julia-assign-the-diagonal-values-of-a-matrix-get-error-in-method-definition), [2の参考](https://docs.julialang.org/en/v1/stdlib/LinearAlgebra/#LinearAlgebra.Diagonal)

## 19. 8x8 行列を生成して、市松模様で埋める

#### 1. numpy100-exerciseと同じアプローチ

In [101]:
ans19_1=zeros(Int64,8,8);

In [102]:
ans19_1[2:2:end,1:2:end].=1;
ans19_1[1:2:end,2:2:end].=1;

In [103]:
ans19_1

8×8 Array{Int64,2}:
 0  1  0  1  0  1  0  1
 1  0  1  0  1  0  1  0
 0  1  0  1  0  1  0  1
 1  0  1  0  1  0  1  0
 0  1  0  1  0  1  0  1
 1  0  1  0  1  0  1  0
 0  1  0  1  0  1  0  1
 1  0  1  0  1  0  1  0

#### 2. `repeat`を用いる

In [109]:
pa=[0 1; 1 0]

2×2 Array{Int64,2}:
 0  1
 1  0

In [112]:
ans19_2=repeat(pa, 4, 4)

8×8 Array{Int64,2}:
 0  1  0  1  0  1  0  1
 1  0  1  0  1  0  1  0
 0  1  0  1  0  1  0  1
 1  0  1  0  1  0  1  0
 0  1  0  1  0  1  0  1
 1  0  1  0  1  0  1  0
 0  1  0  1  0  1  0  1
 1  0  1  0  1  0  1  0

#### 所感・考察・調査
pythonとは異なりjuliaでは`[start:step:end]`の順で指定することに再度注意   
repeat使うのは題意にそわないかもだがnumpyのrepeatより便利でわかりやすい[参考](https://cheatsheets.quantecon.org/julia-cheatsheet.html)

numpyでもやってるもっと大きい塊はindexの指定を対応させるだけなので飛ばしてrepeat使ってやってみる.

※[BlockArrays](https://github.com/JuliaArrays/BlockArrays.jl)って言うパッケージもあるみたい. [使い方の一例](https://stackoverflow.com/questions/54515769/how-do-i-efficiently-construct-a-block-matrix-of-the-following-form-in-julia)

In [114]:
pa_a=[1 1 0 0;1 1 0 0; 0 0 1 1;0 0 1 1]
ans19_a=repeat(pa_a,2,2)

8×8 Array{Int64,2}:
 1  1  0  0  1  1  0  0
 1  1  0  0  1  1  0  0
 0  0  1  1  0  0  1  1
 0  0  1  1  0  0  1  1
 1  1  0  0  1  1  0  0
 1  1  0  0  1  1  0  0
 0  0  1  1  0  0  1  1
 0  0  1  1  0  0  1  1

## 20. shape属性が (6,7,8) の配列のとき、100 番目の要素の添え字 (x,y,z)は？

In [116]:
base20=rand(6,7,8);

In [131]:
base20[100]

0.5018030869420558

#### 所感・考察・調査
これに関してはjuliaの方が便利？

## 21.  repeat(tile) 関数を使って 8x8 の市松模様の行列を生成する

In [2]:
pa=[0 1; 1 0]

2×2 Array{Int64,2}:
 0  1
 1  0

In [3]:
ans21=repeat(pa, 4, 4)

8×8 Array{Int64,2}:
 0  1  0  1  0  1  0  1
 1  0  1  0  1  0  1  0
 0  1  0  1  0  1  0  1
 1  0  1  0  1  0  1  0
 0  1  0  1  0  1  0  1
 1  0  1  0  1  0  1  0
 0  1  0  1  0  1  0  1
 1  0  1  0  1  0  1  0

#### 所感・考察・調査
juliaでは`repeat`関数がpythonの`tile`関数的な立ち位置？

## 22. 5x5 の乱数の行列を正規化する

In [5]:
base22=rand(5,5);

In [32]:
ans22=map(x -> (x-findmin(base22)[1])/(findmax(base22)[1]-findmin(base22)[1]), base22)

5×5 Array{Float64,2}:
 0.225745  0.503401   0.390656  0.0        0.498111  
 0.591373  0.0371045  0.800711  0.0489565  0.408724  
 1.0       0.793097   0.385142  0.513221   0.00901402
 0.931503  0.0369867  0.595053  0.912737   0.224504  
 0.897668  0.891797   0.974115  0.638756   0.237521  

#### 所感・考察・調査
map使わなくてもなんかメソッドありそう要調査

## 23. 色を 4 個の符号なしバイト型 (RGBA) で表現するカスタム dtype を作成する

In [16]:
struct color
    r::Float64
    g::Float64
    b::Float64
    a::Float64
end

In [17]:
[color(100,111,221,12),color(10,11,21,12)]

2-element Array{color,1}:
 color(100.0, 111.0, 221.0, 12.0)
 color(10.0, 11.0, 21.0, 12.0)   

#### 所感・考察・調査
これでいいのか…? [参考](https://docs.julialang.org/en/v1/manual/types/)

## 24. 5x3 行列と 3x2 行列の掛け算 (実数の行列積) 

In [21]:
base24_1=reshape(0:14, 3, 5)';
base24_2=reshape(0:5, 2, 3)';

In [22]:
base24_1*base24_2

5×2 Array{Int64,2}:
 10   13
 28   40
 46   67
 64   94
 82  121

#### 所感・考察・調査
単純に掛け算でできるっぽい、行列の生成のステップの方向がnumpyと違い行方向なのでそこだけ注意

## 25. 1次元配列が与えられたとき、数値が３から８の全要素をネゲート(負値)する

In [74]:
base25=[x for x = 0:10];
tar=-1
ans25=[(if (i>=3) & (i<=8) tar else i end) for i in base25]
print(ans25)

[0, 1, 2, -1, -1, -1, -1, -1, -1, 9, 10]

#### 所感・考察・調査
内包表記もできるっぽい