# Julia100 Exercise
[これ](https://github.com/rougier/numpy-100/blob/master/100_Numpy_exercises.ipynb)をJuliaでやってく.  
もう１つのJulia100exerciseも途中まで(48個くらい？)だけどあるっぽい[こちら](https://github.com/chezou/julia-100-exercises/blob/master/README.md)　　

**目指すは世界初()のJulia100 Exercise作成**

全てに所感と考察を絶対述べる縛りで行きます.

## 1. 行列ライブラリを読み込む（難易度１）

**これはimportの必要なしJuliaに関しては行列計算のライブラリがある**  
ドキュメントは[こちら](https://docs.julialang.org/en/v1/index.html)

## 2. Juliaのバージョンを確認する（難易度１）

In [1]:
VERSION

v"1.2.0"

In [18]:
?VERSION　# ?でドキュメントは変わらないっぽい

search: VERSION VersionNumber versioninfo reverseind



```
VERSION
```

A `VersionNumber` object describing which version of Julia is in use. For details see [Version Number Literals](@ref man-version-number-literals).


#### 所感・考察・調査
演算子の数とかドキュメントの充実さスゴない？(以下参照)

In [21]:
?

search: ⊻ ⊋ ⊊ ⊉ ⊈ ⊇ ⊆ ≥ ≤ ≢ ≡ ≠ ≉ ≈ ∪ ∩ ∛ √ ∘ ∌ ∋ ∉ ∈ ℯ π ÷ ~ | ^ \ > < : / - +



**Welcome to Julia 1.2.0.** The full manual is available at

```
https://docs.julialang.org/
```

as well as many great tutorials and learning resources:

```
https://julialang.org/learning/
```

For help on a specific function or macro, type `?` followed by its name, e.g. `?cos`, or `?@time`, and press enter. Type `;` to enter shell mode, `]` to enter package mode.


In [27]:
?cos

search: cos cosh cosd cosc cospi acos acosh acosd sincos const close isconst



```
cos(x)
```

Compute cosine of `x`, where `x` is in radians.

---

```
cos(A::AbstractMatrix)
```

Compute the matrix cosine of a square matrix `A`.

If `A` is symmetric or Hermitian, its eigendecomposition ([`eigen`](@ref)) is used to compute the cosine. Otherwise, the cosine is determined by calling [`exp`](@ref).

# Examples

```jldoctest
julia> cos(fill(1.0, (2,2)))
2×2 Array{Float64,2}:
  0.291927  -0.708073
 -0.708073   0.291927
```


## 3. サイズ10の零ベクトルを作成する（難易度１）

In [6]:
a = zeros(Float64,10,1)

10×1 Array{Float64,2}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [42]:
zeros(10,1) # 型は指定しないとFloat64

10×1 Array{Float64,2}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [8]:
zeros(10) # 配列になってるっぽい？

10-element Array{Float64,1}:
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0
 0.0

In [5]:
A = zeros(Int64,2,2) 

2×2 Array{Int64,2}:
 0  0
 0  0

#### 所感・考察・調査
あくまでも行列演算ライブラリではないと言うのが`zeros(10)`の結果から読み取れる

## 4. 行列のメモリサイズを確認するには？（難易度１）

In [36]:
sizeof(a)　

80

In [43]:
sizeof(A) #行列じゃなくてももちろん使える

32

In [41]:
# ?size #?のサーチで見つけた。。。

In [40]:
?sizeof

search: sizeof



```
sizeof(T::DataType)
sizeof(obj)
```

Size, in bytes, of the canonical binary representation of the given `DataType` `T`, if any. Size, in bytes, of object `obj` if it is not `DataType`.

# Examples

```jldoctest
julia> sizeof(Float32)
4

julia> sizeof(ComplexF64)
16

julia> sizeof(1.0)
8

julia> sizeof([1.0:10.0;])
80
```

If `DataType` `T` does not have a specific size, an error is thrown.

```jldoctest
julia> sizeof(AbstractArray)
ERROR: Abstract type AbstractArray does not have a definite size.
Stacktrace:
[...]
```

---

```
sizeof(str::AbstractString)
```

Size, in bytes, of the string `str`. Equal to the number of code units in `str` multiplied by the size, in bytes, of one code unit in `str`.

# Examples

```jldoctest
julia> sizeof("")
0

julia> sizeof("∀")
3
```


#### 所感・考察・調査
元のnumpy100見たく`size`とか`itemsize`でやるのかなーと思ってたけど`sizeof()`一発で行けるっぽい

## 5. 任意のfunction等のドキュメントを得るには？（難易度１）

In [44]:
?sin

search: sin sinh sind sinc sinpi sincos asin using isinf asinh asind isinteger



```
sin(x)
```

Compute sine of `x`, where `x` is in radians.

---

```
sin(A::AbstractMatrix)
```

Compute the matrix sine of a square matrix `A`.

If `A` is symmetric or Hermitian, its eigendecomposition ([`eigen`](@ref)) is used to compute the sine. Otherwise, the sine is determined by calling [`exp`](@ref).

# Examples

```jldoctest
julia> sin(fill(1.0, (2,2)))
2×2 Array{Float64,2}:
 0.454649  0.454649
 0.454649  0.454649
```


In [45]:
?fill

search: fill fill! finally findall filter filter! filesize filemode isfile



```
fill(x, dims)
```

Create an array filled with the value `x`. For example, `fill(1.0, (5,5))` returns a 5×5 array of floats, with each element initialized to `1.0`.

# Examples

```jldoctest
julia> fill(1.0, (5,5))
5×5 Array{Float64,2}:
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
 1.0  1.0  1.0  1.0  1.0
```

If `x` is an object reference, all elements will refer to the same object. `fill(Foo(), dims)` will return an array filled with the result of evaluating `Foo()` once.


#### 所感・考察・調査
`?`:ヘルプコマンドの便利さがスゴイ

## 06. 5番目の要素だけ1の大きさ10の零ベクトルを作る（難易度1）

In [5]:
a6 = zeros(10,1)
a6[5]=1

1

In [6]:
a6

10×1 Array{Float64,2}:
 0.0
 0.0
 0.0
 0.0
 1.0
 0.0
 0.0
 0.0
 0.0
 0.0

#### 所感・考察・調査
indexの始まりが0スタートでないことに注意

## 07. 10~49の範囲のベクトルを作成する（難易度1）

In [30]:
LinRange(10,49,49-9)

40-element LinRange{Float64}:
 10.0,11.0,12.0,13.0,14.0,15.0,16.0,17.0,…,43.0,44.0,45.0,46.0,47.0,48.0,49.0

In [61]:
print([ 10 + 1*x for x in 1:39, y in 1:1 ])

[11; 12; 13; 14; 15; 16; 17; 18; 19; 20; 21; 22; 23; 24; 25; 26; 27; 28; 29; 30; 31; 32; 33; 34; 35; 36; 37; 38; 39; 40; 41; 42; 43; 44; 45; 46; 47; 48; 49]

#### 所感・考察・調査
他に絶対いいやり方ありそう、要調査

## 08. ベクトルを並びを反対にするには？(最初の要素を最後の要素に)（難易度1)

In [60]:
base_vec08=[ 10 + 1*x for x in 1:39, y in 1:1 ];

In [56]:
print(base_vec08[end:-1:1])

[49, 48, 47, 46, 45, 44, 43, 42, 41, 40, 39, 38, 37, 36, 35, 34, 33, 32, 31, 30, 29, 28, 27, 26, 25, 24, 23, 22, 21, 20, 19, 18, 17, 16, 15, 14, 13, 12, 11]

#### 所感・考察・調査
arrayのスライス?の使い方?  
`[始めるindex:step:終わりのindex]`,[参考](https://stackoverflow.com/questions/27411401/julia-reverse-n-dimensional-arrays)

In [59]:
print(base_vec08[end:-2:10])

[49, 47, 45, 43, 41, 39, 37, 35, 33, 31, 29, 27, 25, 23, 21]

## 09. 0~8の値をもつ3*3の行列を作成する

In [96]:
base09=[ x-1 for x in 1:9, y in 1:1 ];
ans09=reshape(base09,3,3)'

3×3 LinearAlgebra.Adjoint{Int64,Array{Int64,2}}:
 0  1  2
 3  4  5
 6  7  8

#### 所感・考察・調査
これはnumpyとほぼ同じ、転置するには`'`をつける。[参考](https://qiita.com/haru1843/items/3956dab2fd0d448cd02b)